name: Build

on:
  push:
    branches: [ "develop", "feature/code_coverage" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
     run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" --settings Tests/testsettings.xml --results-directory ./TestResults
    - name: Test Results
      uses: NasAmin/trx-parser@v0.2.0
      id: trx-parser
      with:
        TRX_PATH: ${{ github.workspace }}/src/TestResults
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'src/TestResults/**/coverage.cobertura.xml'
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        indicators: true
        output: both
        thresholds: '95 95'
        badge: true
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: 'code-coverage-report.md'